name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push Backend Folder Only
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
          # 1. Enter the Backend folder
          cd Backend
          
          # 2. Initialize a new "temporary" git repo just for this folder
          git init
          git branch -m main
          
          # 3. Set up LFS (Vital for your model file)
          git lfs install
          git lfs track "*.pth"
          
          # 4. Add all files in this folder (including the new README.md you just made)
          git add .
          git commit -m "Deploy Backend Service"
          
          # 5. Force push THIS FOLDER to Hugging Face
          git remote add space https://akshay1306:$HF_TOKEN@huggingface.co/spaces/akshay1306/moodquest-api
          git push --force space main